### ISSUE TITLE
Error when running gpt2bs tutorial

### ISSUE THREAD

**Issue by hSterz** [microsoft/onnxruntime-extensions#150]
The gpt2bs tutorial linked in the ReadMe seems to be not working. When I download the file and run it without any changes I get the following Error:
site-packages\onnxruntime_extensions\onnxprocess\_tensor.py", line 264, in __getattribute__
    return object.__getattribute__(self, attr)
AttributeError: '_EagerTensor' object has no attribute 'dtype'

**Comment by wenbingl** [comment]
I just tried the last builds from master, it works with transformers==4.5.1.
You can build and install the package by

_python setup.py develop_

after you clone this git repo

We will release a new pypi package very soon (probably late next week), you can wait for it if you don't want to build package on your own.

**Comment by GeorgeS2019** [comment]
@hSterz
gpt2bs has been replaced with no error code.

Perhaps close this issue
